### ISSUE TITLE
Expired link

### ISSUE THREAD

**Issue by thunguyenuehk39** [AemikaChow/CLOTH4D#3]
Hi team,

Thank you for your dataset. However, the link is expired. Can you publish it again?

Thank you so much

**Comment by AemikaChow** [comment]
> Hi team,
> 
> Thank you for your dataset. However, the link is expired. Can you publish it again?
> 
> Thank you so much

Thanks for your interest. You may use the new link https://hkaidlab-my.sharepoint.com/:f:/g/personal/xingxingzou_aidlab_hk/EtOAImdFKedMgezprRQiJBIBcCnvJEp7yRaLB8kZKlWNzw?e=OxSCy5 for downloading.

**Comment by thunguyenuehk39** [comment]
Thank you so much
