### ISSUE TITLE
Why the smpl model has hair?

### ISSUE THREAD

**Issue by Moronrift08** [AemikaChow/CLOTH4D#7]
![image](https://github.com/user-attachments/assets/41e400b0-0842-48dc-ad65-33bb05dcab66)
The previous datasets didn't contain hair in their smplx model
Could you please tell me why?

**Comment by xthan** [comment]
This is not the SMPL-X model. It is the naked human mesh exported using CLO. To obtain a SMPL-X model, you need to run a registration process as mentioned in Section 3 "Paired Multi-Modal Data" in the main paper and detailed in Section 5 in the supplementary material. A simplified version of fitting a SMPL model to the naked human mesh can be found here https://github.com/xthan/smplreg/

**Comment by Moronrift08** [comment]
Thanks for your reply.
