### ISSUE TITLE
.pkl files are not found in CLOTH4D dataset

### ISSUE THREAD

**Issue by Moronrift08** [AemikaChow/CLOTH4D#8]
![image](https://github.com/user-attachments/assets/0a5c3b53-8227-44b6-bfb5-3359f3adbd19)

Hi, thanks for your excellent work!

According to this program for the smpl registration, it needs the initial estimation parameters of SMPL parameters.
I noticed that in your examples, you provide such a .pkl file but for there are no related files in the CLOTH4D dataset
So I'm wondering where can I find it?
Thanks in advance for your kind reply.

**Comment by xthan** [comment]
Hi, thanks for your interest in our work!

The .pkl file is generated by running an HMR network like GraphCMR or PyMaf on the RGB image. You can have a look at the sample .pkl file and write the results of PyMaf in the same format. There may be more advanced HMR models recently that you can use to obtain a more accurate initial estimation of SMPL parameters.

**Comment by Moronrift08** [comment]
Thanks for your kind reply!
